### ISSUE TITLE
not support 'ply' format?

### ISSUE THREAD

**Issue by MandyDongrs** [francisengelmann/PyViz3D#6]
Does it only support the 'obj' format of meshes and point cloud?

**Comment by francisengelmann** [comment]
Hi!
Point clouds do not depend on any specific format, you only need the point positions (and if available color / normals).
Here is an [example](https://github.com/francisengelmann/PyViz3D/blob/master/examples/example_point_clouds.py)

For meshes, at the moment it only supports .obj - but you are more than welcome to create a pull request - I think it is just another data loader, should be rather straightforward - if you can wait "some time" I can also add it at some point :)

**Comment by MandyDongrs** [comment]
Thanks very much! Your project is really user-friendly, light weight and elegant!
By the way, I found your code depends on Threejs. Maybe it may be better to add relevant documentations to your readme file for a good understanding about the details on coordinate systems and transformations.







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "francisengelmann/PyViz3D"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月14日(星期四) 下午3:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [francisengelmann/PyViz3D] not support 'ply' format? (Issue #6)





 
Hi!
 Point clouds do not depend on any specific format, you only need the point positions (and if available color / normals).
 Here is an example
 
For meshes, at the moment it only supports .obj - but you are more than welcome to create a pull request - I think it is just another data loader, should be rather straightforward - if you can wait "some time" I can also add it at some point :)
