### ISSUE TITLE
Issue with new version of Three JS

### ISSUE THREAD

**Issue by ywyue** [francisengelmann/PyViz3D#7]
Hi Francis, I found a problem with the lastest release. The error is with this [line](https://github.com/francisengelmann/PyViz3D/blob/9e80d259e0a1a26848c5cc086f4104880359b344/pyviz3d/src/js/scene.js#L223). 

![image](https://user-images.githubusercontent.com/40747438/210099300-3d2741c6-12a0-4168-94a6-2bd647ba6655.png)

![image](https://user-images.githubusercontent.com/40747438/210099328-870019f0-ad3e-4091-8975-fb66b5aa3ded.png)

In the lastest version of Three JS, **CylinderGeometry** (also **SphereGeometry**) has no attributes of **faces**.

After I replace [import * as THREE from 'three';](https://github.com/francisengelmann/PyViz3D/blob/9e80d259e0a1a26848c5cc086f4104880359b344/pyviz3d/src/js/scene.js#L1) with `import * as THREE from 'https://threejsfundamentals.org/threejs/resources/threejs/r112/build/three.module.js';`, it works fine

Yuanwen

**Comment by francisengelmann** [comment]
Hi Yuanwen,

Thanks for pointing this out!
I just fixed it, you can install the latest release - if you find sth else please let me know.

Best,
Francis
